
const {onRequest} = require("firebase-functions/v2/https");
const logger = require("firebase-functions/logger");
require("dotenv").config();


exports.main = onRequest((request, response) => {
  logger.info("Hello logs!", {structuredData: true});
  response.json([
    {
      "aak": process.env.AAK,
      "ask": process.env.ASK,
    },
    {
      "id": "B0CFB132B5",
      "title": "Ougenni Sunglasses for Women Men Vintage Polarized Women Sunglasses Round Classic Retro UV Protection Lens",
      "price": "15.99",
      "realPrice": "15.99",
      "category": "Beauty",
      "link": "https://amzn.to/3FXGkur",
      "imageDeal": "https://m.media-amazon.com/images/I/61hPx+wF99L._AC_SY695_.jpg",
      "couponText": "50SQPIZD6190",
      "couponEndTimeEpoch": 1744059600,
      "couponExtra": 0.5,
    },
    {
      "id": "B0BJJ2WLVT",
      "title": "LED Strip Lights 100ft, Bluetooth and APP Control, Multicolor RGB Light Strips, Music Sync Color Changing for Bedroom Indoor",
      "price": "19.98",
      "realPrice": "19.98",
      "category": "Home",
      "link": "https://amzn.to/4iZPR2K",
      "imageDeal": "https://m.media-amazon.com/images/I/71ysjPQPUBL._AC_SL1500_.jpg",
      "couponText": "50BT3QRI",
      "couponEndTimeEpoch": 1746305940,
      "couponExtra": 0.5,
    },
    {
      "id": "B0916XH8PJ",
      "title": "Silvervine Sticks for Cats, 30PCS Kitten Toys Catnip Toys Matatabi Silvervine Sticks Kitty Chew Toys Wooden Stick Kitten Teething Toys Molar Suitable for Cats of All Ages",
      "price": "9.99",
      "realPrice": "9.99",
      "category": "Pet",
      "link": "https://amzn.to/3E94eT4",
      "imageDeal": "https://m.media-amazon.com/images/I/71HRqoYX9hL._AC_SL1500_.jpg",
      "couponText": "50H1ZLAC",
      "couponEndTimeEpoch": 1744491540,
      "couponExtra": 0.5,
    },
    {
      "id": "B0CT5ZJHNX",
      "title": "Baby Fruit Feeder, with Mini Freezer Tray, Silicone Teething Toys, Breastmilk Popsicle Molds for Baby Teething Relief, Includes 4 Mesh Pacifier",
      "price": "9.99",
      "realPrice": "9.99",
      "category": "Baby",
      "link": "https://amzn.to/4i82nMm",
      "imageDeal": "https://m.media-amazon.com/images/I/71noIk8bmkL._SL1500_.jpg",
      "couponText": "4077ROQS",
      "couponEndTimeEpoch": 1746046740,
      "couponExtra": 0.4,
    },
    {
      "id": "B082SV3RZQ",
      "title": "Easter Bunny Basket Egg Bags for Kids,Canvas Cotton Personalized Candy Egg Basket Rabbit Print Buckets with Fluffy Tail Gifts Bags for Easter\u2026\u2026",
      "price": "9.99",
      "realPrice": "9.99",
      "imageDeal": "https://m.media-amazon.com/images/I/710tCFB534L._SL1500_.jpg",
      "category": "Baby",
      "link": "https://amzn.to/3RAdORZ",
      "couponText": "502JYGYD",
      "couponEndTimeEpoch": 1745182740,
      "couponExtra": 0.5,
    },
    {
      "id": "B07L3WBJYT",
      "title": "VS VOGSHOW Diaper Bag Backpack, Multifunction Stylish Travel Baby Bag Backpack with Crossbody Strap, Maternity Nappy Bag",
      "price": "39.99",
      "realPrice": "39.99",
      "category": "Baby",
      "link": "https://amzn.to/42tCmlX",
      "imageDeal": "https://m.media-amazon.com/images/I/81OCsXzAWFL._AC_SL1500_.jpg",
      "couponText": "50TND5DX",
      "couponEndTimeEpoch": 1745182740,
      "couponExtra": 0.5,
    },
    {
      "id": "B0D7TMYFRJ",
      "title": "Magnetic Blocks,Creative Building Toys for Kids, STEM Sensory Toys for Ages 3-5, 5-7, 8-13, Christmas Birthday Gifts for Boys &amp; Girls",
      "price": "39.99",
      "realPrice": "39.99",
      "category": "Baby",
      "link": "https://amzn.to/3Rzkj7E",
      "imageDeal": "https://m.media-amazon.com/images/I/81Y4jJljquL._AC_SL1500_.jpg",
      "couponText": "207LWLGM",
      "couponEndTimeEpoch": 1745182740,
      "couponExtra": 0.2,
    },
    {
      "id": "B0DN6QWZLJ",
      "title": "Magnetic Tiles 102pcs Frozen Princess Castle Toys Magnetic Building Blocks 3 4 5 6 7 8 Year Old Girl Gifts Girls Toys Age 4-5 6-8 9-12",
      "price": "39.99",
      "realPrice": "69.99",
      "category": "Baby",
      "link": "https://amzn.to/44fbXJU",
      "imageDeal": "https://m.media-amazon.com/images/I/917SJhFSCoL._AC_SL1500_.jpg",
      "couponText": "45PV5HW4",
      "couponEndTimeEpoch": 1766340961,
      "couponExtra": 0.45,
    },
  ]);
});
