
const {onRequest} = require("firebase-functions/v2/https");
const {defineSecret} = require("firebase-functions/params");
const logger = require("firebase-functions/logger");

const aak = defineSecret("AAK");
const ask = defineSecret("ASK");

exports.main = onRequest({secrets: [aak, ask]}, (request, response) => {
  logger.info("Hello logs!", {structuredData: true});
  response.json([
    {
      "aak": aak.value(),
      "ask": ask.value(),
    },
    {
      "id": "B0CFB132B5",
      "title": "Ougenni Sunglasses for Women Men Vintage Polarized Women Sunglasses Round Classic Retro UV Protection Lens",
      "price": "15.99",
      "realPrice": "15.99",
      "category": "Beauty",
      "link": "https://amzn.to/3FXGkur",
      "imageDeal": "https://m.media-amazon.com/images/I/61hPx+wF99L._AC_SY695_.jpg",
      "couponText": "50SQPIZD6190",
      "couponEndTimeEpoch": 1782808908,
      "couponExtra": 0.5,
    },
    {
      "id": "B0FWCVK1RQ",
      "title": "Led Garage Lights Bulb 10 Pack 120W Super Bright Ceiling Led Shop Lights 6 Deformable Panels Screw in E26/E27 6500K 12000 LM Deformable Garage Light Ideal for Basement Attic and Workshop",
      "price": "59.99",
      "realPrice": "119.99",
      "category": "Home Improvement",
      "link": "https://www.amazon.com/dp/B0FWCVK1RQ?tag=dealszone001-20",
      "imageDeal": "https://m.media-amazon.com/images/I/71cXSE6T+hL.jpg",
      "couponText": "6C9VXY8O",
      "couponEndTimeEpoch": 1780815540,
      "couponExtra": 0.5,
    },
    {
      "id": "B00YI5VJW6",
      "title": "Auraglow Teeth Whitening Kit, LED Accelerator Light, 35% Carbamide Peroxide Teeth Whitening Gel, 20+ Whitening Treatments, Whitens up to 10 Shades in 7 Days",
      "price": "45.60",
      "realPrice": "48.00",
      "category": "Beauty & Grooming",
      "link": "https://www.amazon.com/dp/B00YI5VJW6?tag=dealszone001-20",
      "imageDeal": "https://m.media-amazon.com/images/I/610DA7ixPiL.jpg",
      "couponText": "IJ9NID6I",
      "couponEndTimeEpoch": 1782889140,
      "couponExtra": 0.05,
      "details": [
        "POWERFUL WHITENING KIT — Most powerful teeth whitening kit that uses an LED light with 35% carbamide peroxide gel to whiten teeth faster. Removes common daily stains from coffee, tea, wine, and smoking.",
        "PROFESSIONAL-LEVEL WHITENING — Achieve professional level whitening results at home with our LED teeth whitening kit. Similar to in-office dental laser whitening treatments.",
        "WHITENS FASTER — The LED light activates the molecules in the bleaching gel to whiten teeth faster and remove years of stains in just 30 minutes. Experience a whiter smile at home in without expensive dental treatments.",
        "LED ACCELERATOR SYSTEM — The whitening gel performs the whitening while the LED light helps evenly activate and distribute the gel across teeth for consistent coverage during each treatment.",
        "ALTERNATIVE TO WHITENING STRIPS — The mouth tray allows controlled application to each tooth and helps avoid uneven whitening or slipping that can occur with strips while using concentrated gel.",
      ],
    },
    {
      "id": "B0G6WMY2WW",
      "title": "4-IN-1 Detachable Cosmetic Bag, Foldable Waterproof PU Leather Makeup Bag, Portable Travel Toiletry Organizer Bag for Women Daily & Travel Use (Premium Gray)",
      "price": "18.99",
      "realPrice": "18.99",
      "category": "Clothing & Accessories",
      "link": "https://www.amazon.com/dp/B0G6WMY2WW?tag=dealszone001-20",
      "imageDeal": "https://m.media-amazon.com/images/I/71ZqqQ8V6jL.jpg",
      "couponText": "DNI5P3M4",
      "couponEndTimeEpoch": 1780901940,
      "couponExtra": 0.4,
      "details": [
        "4-IN-1 Detachable Compartments Design: Features 4 independent zippered pockets to neatly organize skincare, cosmetics, makeup brushes and small accessories, eliminating messy searching. Each pouch is detachable for separate use, perfect for on-the-go convenience.",
        "Foldable & Space-Saving Travel Design: Expands into a desktop organizer for easy access to all products, and folds into a compact carry bag for ultra-portability. Ideal for business trips, vacations, weekend getaways and daily use.",
        "Premium Waterproof PU Material: Made of high-quality textured PU leather that is waterproof, stain-resistant and scratch-proof, easy to clean with a simple wipe. The smooth finish delivers a luxurious look for your travel essentials.",
        "Large Capacity & Compact Structure: Generously holds full-size toiletries, lotions, serums, makeup palettes, brushes, sunglasses and more, all in one bag without adding extra bulk to your luggage.",
        "Versatile for Daily & Travel Use: Doubles as a cosmetic bag, toiletry pouch, makeup case and desktop organizer. A stylish and practical storage solution for women who value order, elegance and functionality.",
      ],
    },
    {
      "id": "B0916XH8PJ",
      "title": "Silvervine Sticks for Cats, 30PCS Kitten Toys Catnip Toys Matatabi Silvervine Sticks Kitty Chew Toys Wooden Stick Kitten Teething Toys Molar Suitable for Cats of All Ages",
      "price": "9.99",
      "realPrice": "9.99",
      "category": "Pet",
      "link": "https://amzn.to/3E94eT4",
      "imageDeal": "https://m.media-amazon.com/images/I/71HRqoYX9hL._AC_SL1500_.jpg",
      "couponText": "50H1ZLAC",
      "couponEndTimeEpoch": 1744491540,
      "couponExtra": 0.5,
    },
    {
      "id": "B0CT5ZJHNX",
      "title": "Baby Fruit Feeder, with Mini Freezer Tray, Silicone Teething Toys, Breastmilk Popsicle Molds for Baby Teething Relief, Includes 4 Mesh Pacifier",
      "price": "9.99",
      "realPrice": "9.99",
      "category": "Baby",
      "link": "https://amzn.to/4i82nMm",
      "imageDeal": "https://m.media-amazon.com/images/I/71noIk8bmkL._SL1500_.jpg",
      "couponText": "4077ROQS",
      "couponEndTimeEpoch": 1746046740,
      "couponExtra": 0.4,
    },
    {
      "id": "B082SV3RZQ",
      "title": "Easter Bunny Basket Egg Bags for Kids,Canvas Cotton Personalized Candy Egg Basket Rabbit Print Buckets with Fluffy Tail Gifts Bags for Easter\u2026\u2026",
      "price": "9.99",
      "realPrice": "9.99",
      "imageDeal": "https://m.media-amazon.com/images/I/710tCFB534L._SL1500_.jpg",
      "category": "Baby",
      "link": "https://amzn.to/3RAdORZ",
      "couponText": "502JYGYD",
      "couponEndTimeEpoch": 1745182740,
      "couponExtra": 0.5,
    },
    {
      "id": "B07L3WBJYT",
      "title": "VS VOGSHOW Diaper Bag Backpack, Multifunction Stylish Travel Baby Bag Backpack with Crossbody Strap, Maternity Nappy Bag",
      "price": "39.99",
      "realPrice": "39.99",
      "category": "Baby",
      "link": "https://amzn.to/42tCmlX",
      "imageDeal": "https://m.media-amazon.com/images/I/81OCsXzAWFL._AC_SL1500_.jpg",
      "couponText": "50TND5DX",
      "couponEndTimeEpoch": 1745182740,
      "couponExtra": 0.5,
    },
    {
      "id": "B0D7TMYFRJ",
      "title": "Magnetic Blocks,Creative Building Toys for Kids, STEM Sensory Toys for Ages 3-5, 5-7, 8-13, Christmas Birthday Gifts for Boys &amp; Girls",
      "price": "39.99",
      "realPrice": "39.99",
      "category": "Baby",
      "link": "https://amzn.to/3Rzkj7E",
      "imageDeal": "https://m.media-amazon.com/images/I/81Y4jJljquL._AC_SL1500_.jpg",
      "couponText": "207LWLGM",
      "couponEndTimeEpoch": 1745182740,
      "couponExtra": 0.2,
    },
    {
      "id": "B0DN6QWZLJ",
      "title": "Magnetic Tiles 102pcs Frozen Princess Castle Toys Magnetic Building Blocks 3 4 5 6 7 8 Year Old Girl Gifts Girls Toys Age 4-5 6-8 9-12",
      "price": "39.99",
      "realPrice": "69.99",
      "category": "Baby",
      "link": "https://amzn.to/44fbXJU",
      "imageDeal": "https://m.media-amazon.com/images/I/917SJhFSCoL._AC_SL1500_.jpg",
      "couponText": "45PV5HW4",
      "couponEndTimeEpoch": 1766340961,
      "couponExtra": 0.45,
    },
  ]);
});
