@echo off
echo Closing Chrome...
taskkill /F /IM chrome.exe >nul 2>&1
timeout /t 2 /nobreak >nul
echo Starting Chrome with debugging...
"C:\Program Files\Google\Chrome\Application\chrome.exe" --remote-debugging-port=9222 --user-data-dir="C:\Users\vesko\AppData\Local\Google\Chrome\User Data" --profile-directory=Default
